name: sentra_ui
description: "Sentra Standalone Design System"
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mix: any
  google_fonts: any
  lucide_icons_flutter: any
  flutter_screenutil: any
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
